myapp:
  build: .
  command: node_modules/.bin/nodemon index.js
  container_name: myapp
  environment:
    NODE_ENV: dev
  ports:
    - '3000:3000'
  volumes:
    - .:/home/app/myapp
    - /home/app/myapp/node_modules
